apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_CONNECTION_STRING: bXlzcWw6Ly9hZG1pbjpIYWRpeWFwcm9kdWN0QGhhZGl5YS0xLmNkZWU4dXcwcTNkdC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206MzMwNi9oYWRpeWE=
  
